test_that("cast works", {
  x <- new_weeknumber(1000)
  expect_equal(as_weeknumber(1000), x)
  expect_equal(as_weeknumber("2019-W10"), x)
  expect_equal(as_weeknumber(factor("2019-W10")), x)
  expect_equal(as_weeknumber(x), x)
  expect_equal(as_weeknumber(lubridate::make_date(2019, 3, 7)), x)
  y <- lubridate::make_datetime(2019, 3, 7, 12)
  expect_equal(as_weeknumber(y), x)
  expect_equal(as_weeknumber(as.POSIXlt(y)), x)
})
